### ISSUE TITLE
Will not compile

### ISSUE THREAD

**Issue by masterhash-us** [CriptoReal/Criptoreal#1]
Makefile.am:78: error: CPPFLAGS_FOR_BUILD must be set with '=' before using '+='
Makefile.am:79: error: CFLAGS_FOR_BUILD must be set with '=' before using '+='

**Comment by CriptoRealDev** [comment]
Please read manual:
https://github.com/CriptoReal/Criptoreal/blob/master/doc/build-unix.md#dependency-build-instructions-ubuntu--debian

You have dependencies issues.

Also when you open an issue, please state your OS, otherwise it is impossible to help.
